"use client";

import { Download, Share2, Copy, FileText, CheckCircle2, MoreHorizontal, Layers, ChevronRight, Bookmark, Zap } from "lucide-react";
import { useEffect, useState } from "react";
import { BRAND } from "@/config/branding";

type LatestLectureResponse = {
    lecture: {
        id: string;
        title: string;
        createdAt: string;
        notes: { id: string; content: string } | null;
    } | null;
};

export default function NotesPage() {
    const [copied, setCopied] = useState(false);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [data, setData] = useState<LatestLectureResponse["lecture"]>(null);

    useEffect(() => {
        (async () => {
            try {
                const res = await fetch("/api/lectures/latest");
                if (!res.ok) {
                    throw new Error("Failed to load notes");
                }
                const json: LatestLectureResponse = await res.json();
                setData(json.lecture);
            } catch (e) {
                console.error(e);
                setError("Unable to load notes for your latest lecture.");
            } finally {
                setLoading(false);
            }
        })();
    }, []);

    const content = data?.notes?.content ?? "";

    const handleCopy = () => {
        if (!content) return;
        navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="flex gap-8 max-w-6xl mx-auto pb-10">
            {/* Main Note Reader Column */}
            <div className="flex-1 space-y-6">
                {/* Breadcrumb / Title */}
                    <div className="flex items-center gap-2 text-sm font-bold text-gray-400 mb-6 uppercase tracking-widest">
                        <span className="hover:text-blue-600 transition-colors cursor-pointer">Lectures</span>
                        <ChevronRight className="w-4 h-4" />
                        <span className="hover:text-blue-600 transition-colors cursor-pointer">
                            {data?.title ?? "Latest lecture"}
                        </span>
                        <ChevronRight className="w-4 h-4" />
                        <span className="text-gray-900">Summary</span>
                    </div>

                {/* Document Card */}
                <div className="bg-white border border-gray-100 rounded-[2rem] shadow-[0_10px_40px_rgba(0,0,0,0.03)] overflow-hidden">
                    {/* ActionBar Top */}
                    <div className="flex justify-between items-center px-8 py-5 border-b border-gray-50 bg-gray-50/30">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 bg-blue-50 text-blue-600 flex items-center justify-center rounded-xl shadow-[0_0_15px_rgba(59,130,246,0.1)]">
                                <FileText className="w-5 h-5" />
                            </div>
                            <div>
                                <h2 className="text-lg font-bold text-gray-900">
                                    {data?.title ?? "Upload a lecture to generate notes"}
                                </h2>
                                <p className="text-xs text-gray-400 font-medium tracking-wide">Generated by {BRAND.name}</p>
                            </div>
                        </div>
                        <div className="flex items-center gap-2">
                            <button onClick={handleCopy} className="p-2 text-gray-400 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors shadow-sm bg-white border border-gray-100 relative group">
                                {copied ? <CheckCircle2 className="w-[18px] h-[18px] text-emerald-500" /> : <Copy className="w-[18px] h-[18px]" />}
                                <span className="absolute -bottom-8 right-0 bg-gray-900 text-white text-[10px] px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity font-bold uppercase tracking-widest pointer-events-none">
                                    {copied ? "Copied" : "Copy"}
                                </span>
                            </button>
                            <button className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors shadow-sm bg-white border border-gray-100">
                                <Share2 className="w-[18px] h-[18px]" />
                            </button>
                            <button className="p-2 text-gray-400 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors shadow-sm bg-white border border-gray-100">
                                <MoreHorizontal className="w-[18px] h-[18px]" />
                            </button>
                        </div>
                    </div>

                    {/* Content Body */}
                    <div className="p-8 sm:p-12 lg:px-16 min-h-[400px] text-gray-800 leading-relaxed font-medium">
                        {loading && (
                            <p className="text-sm text-gray-500">Loading your latest notes…</p>
                        )}
                        {!loading && error && (
                            <p className="text-sm text-red-500">{error}</p>
                        )}
                        {!loading && !error && !data && (
                            <div className="text-sm text-gray-500">
                                You don&apos;t have generated notes yet. Upload a lecture from the Upload page to get started.
                            </div>
                        )}
                        {!loading && !error && data && content && (
                            <pre className="whitespace-pre-wrap text-[15px] font-normal text-gray-800">
                                {content}
                            </pre>
                        )}
                    </div>
                </div>
            </div>

            {/* Sticky Context Menu (Sidebar) */}
            <div className="hidden lg:block w-72 shrink-0 space-y-6">

                {/* Save & Export */}
                <div className="bg-white border border-gray-100 rounded-2xl p-6 shadow-[0_4px_30px_rgba(0,0,0,0.02)] sticky top-20">
                    <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-4">Actions</h3>
                    <div className="space-y-3">
                        <button className="w-full flex items-center justify-between p-3 bg-blue-600 hover:bg-blue-700 text-white font-bold text-[13px] rounded-xl shadow-[0_4px_14px_rgba(59,130,246,0.3)] hover:-translate-y-0.5 transition-all">
                            <span className="flex items-center gap-2"><Download className="w-[18px] h-[18px]" /> Export PDF</span>
                        </button>
                        <button className="w-full flex items-center justify-between p-3 bg-white hover:bg-gray-50 text-gray-900 border border-gray-200 font-bold text-[13px] rounded-xl shadow-sm transition-colors">
                            <span className="flex items-center gap-2 text-gray-600"><Bookmark className="w-[18px] h-[18px]" /> Save to Vault</span>
                        </button>
                    </div>

                    <hr className="border-gray-100 my-6" />

                    <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-4">Related Materials</h3>

                    <div className="space-y-4">
                        <div className="flex items-start gap-3 cursor-pointer group">
                            <div className="w-8 h-8 rounded-lg bg-purple-50 flex items-center justify-center shrink-0 border border-purple-100 group-hover:scale-105 transition-transform">
                                <Zap className="w-4 h-4 text-purple-600" />
                            </div>
                            <div>
                                <p className="text-sm font-bold text-gray-900 group-hover:text-purple-600 transition-colors">Thermodynamics Cards</p>
                                <p className="text-xs text-gray-400 font-medium">14 Flashcards</p>
                            </div>
                        </div>
                        <div className="flex items-start gap-3 cursor-pointer group">
                            <div className="w-8 h-8 rounded-lg bg-emerald-50 flex items-center justify-center shrink-0 border border-emerald-100 group-hover:scale-105 transition-transform">
                                <FileText className="w-4 h-4 text-emerald-600" />
                            </div>
                            <div>
                                <p className="text-sm font-bold text-gray-900 group-hover:text-emerald-600 transition-colors">Laws of Physics Quiz</p>
                                <p className="text-xs text-gray-400 font-medium">Score: 90%</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}
